# Generated by Django 4.0.3 on 2022-05-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post_like_post_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
